# Generated by Django 3.0.4 on 2020-03-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOGIN',
            fields=[
                ('Roll', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('pass', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('hostel', models.CharField(max_length=20)),
                ('alloted', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
        migrations.CreateModel(
            name='ROOM',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('occupancy', models.IntegerField(max_length=20)),
                ('aval', models.IntegerField(max_length=20)),
                ('floor', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
