# Generated by Django 3.0.4 on 2020-03-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'managed': False},
        ),
    ]
