# Generated by Django 3.0.4 on 2020-03-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200326_1148'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='Room',
        ),
    ]
